"""create jobs and tasks

Revision ID: 375bc943edb1
Revises: 
Create Date: 2026-09-21 13:57:34.880841

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '375bc943edb1'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('accelerator_type', sa.String(length=64), nullable=False),
    sa.Column('accelerators_per_task', sa.Integer(), nullable=False),
    sa.Column('priority_class', sa.String(length=16), nullable=False),
    sa.Column('input_ref', sa.String(length=2048), nullable=False),
    sa.Column('output_ref', sa.String(length=2048), nullable=False),
    sa.Column('checkpointable', sa.Boolean(), nullable=False),
    sa.Column('replicas', sa.Integer(), nullable=False),
    sa.Column('shards', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('pending_reason', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("priority_class IN ('low', 'normal', 'high')", name='ck_jobs_priority_class'),
    sa.CheckConstraint("state IN ('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELLED')", name='ck_jobs_state'),
    sa.CheckConstraint("type IN ('training', 'batch_inference')", name='ck_jobs_type'),
    sa.CheckConstraint('accelerators_per_task > 0', name='ck_jobs_accelerators_per_task_positive'),
    sa.CheckConstraint('replicas > 0', name='ck_jobs_replicas_positive'),
    sa.CheckConstraint('shards > 0', name='ck_jobs_shards_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.String(length=255), nullable=True),
    sa.Column('checkpoint_ref', sa.String(length=2048), nullable=True),
    sa.Column('output_ref', sa.String(length=2048), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("state IN ('PENDING', 'LEASED', 'COMMITTED', 'FAILED')", name='ck_tasks_state'),
    sa.CheckConstraint('"index" >= 0', name='ck_tasks_index_nonnegative'),
    sa.CheckConstraint('attempt >= 0', name='ck_tasks_attempt_nonnegative'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'index', name='uq_tasks_job_id_index')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    op.drop_table('jobs')
    # ### end Alembic commands ###
