"""add job idempotency fields

Revision ID: 764f7a2c98ca
Revises: 375bc943edb1
Create Date: 2026-09-21 15:51:46.761071

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '764f7a2c98ca'
down_revision: str | Sequence[str] | None = '375bc943edb1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('idempotency_key', sa.String(length=255), nullable=False))
    op.add_column('jobs', sa.Column('request_hash', sa.String(length=64), nullable=False))
    op.create_unique_constraint('uq_jobs_tenant_id_idempotency_key', 'jobs', ['tenant_id', 'idempotency_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_jobs_tenant_id_idempotency_key', 'jobs', type_='unique')
    op.drop_column('jobs', 'request_hash')
    op.drop_column('jobs', 'idempotency_key')
    # ### end Alembic commands ###
