"""add nodes and task leases

Revision ID: 7c1e8c71111b
Revises: 764f7a2c98ca
Create Date: 2026-09-21 16:22:56.862747

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7c1e8c71111b'
down_revision: str | Sequence[str] | None = '764f7a2c98ca'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nodes',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('pool', sa.String(length=255), nullable=False),
    sa.Column('accelerator_type', sa.String(length=64), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('capacity >= 1', name='ck_nodes_capacity_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('tasks', sa.Column('lease_id', sa.String(length=255), nullable=True))
    op.add_column('tasks', sa.Column('epoch', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('tasks', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'expires_at')
    op.drop_column('tasks', 'epoch')
    op.drop_column('tasks', 'lease_id')
    op.drop_table('nodes')
    # ### end Alembic commands ###
